var fecha_solicitud="25-6-2018";
var nombre="meily";
var fecha_nacimiento="27-8-2001";
var correo="meilyjeam@gmail.com";
var telefono=2220432;
var genero="femenino"
var domicilio="casa"
var departamento="antioquia"
var ciudad="medellin"
var direccion="Cra 22 #22c -22"
var numero_integrantes_domicilio=3
var razon_adopcion="compania"
var experiencia="si"
var otra_mascota="si"
var ingresos=500000
var ingresos_mascota=200000
var dedicacion_mascota="4 horas"
var quien_lo_cuidara="papa"